[workspace]
resolver = "2"
members = [
    "crates/openskp",
    "crates/openskp-cli",
    "crates/openskp-capi",
]

[workspace.package]
version = "0.1.3"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/hew3d/openskp"
authors = ["Kurt Granroth <kurt.git@granroth.com>"]

[profile.release]
opt-level = 3
