[package]
name = "openskp-cli"
description = "Command-line reader for SketchUp .skp files"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "openskp"
path = "src/main.rs"

[dependencies]
openskp = { path = "../openskp", version = "0.1.3" }
